@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
hide footbox
actor User
participant ":Astra" as Astra
participant ":Parser" as Parser
participant ":AddTaskCommand" as AddTaskCommand
participant ":Task" as Task
participant ":ActivityList" as ActivityList
participant ":Ui" as Ui
participant ":Notebook" as Notebook

User -> Astra: input "task <desc> /by <date> <time> /priority <n>"
activate Astra
Astra -> Parser : parse(input)
activate Parser

create AddTaskCommand
Parser -> AddTaskCommand : new AddTaskCommand(input)
activate AddTaskCommand
AddTaskCommand --> Parser
deactivate AddTaskCommand

Parser --> Astra : AddTaskCommand
deactivate Parser

Astra -> AddTaskCommand : execute(AL, UI, NB)
activate AddTaskCommand

create Task
AddTaskCommand -> Task
activate Task
Task --> AddTaskCommand
deactivate Task
destroy Task

AddTaskCommand -> ActivityList : addTaskWithPriority(task,int)
activate ActivityList
ActivityList --> AddTaskCommand
deactivate ActivityList

' Show a message through Ui
AddTaskCommand -> Ui : showMessage("Task added successfully")
activate Ui
Ui --> AddTaskCommand
deactivate Ui

' Save to file using Notebook

' Return value to user
AddTaskCommand --> Astra : false
deactivate AddTaskCommand
destroy AddTaskCommand
Astra -> Notebook : saveToFile(activities)
activate Notebook
Notebook --> Astra

Astra -> Notebook : writeToFile(activities)

Notebook --> Astra
deactivate Notebook
Astra -->User
@enduml