@startuml
!include style.puml
actor User
participant Astra as ":Astra"
participant Parser as ":Parser"


participant C as ":AddGpaCommand"


participant GpaEntry as ":GpaEntry"
participant NB as ":Notebook"
participant GL as ":GpaList"
participant UI as ":Ui"


User -> Astra: input \n"add gpa CS2040C A+ 4mc"
activate Astra

Astra -> Parser: parse(input)
activate Parser

create C
Parser --> C: new AddGpaCommand(input)
activate C
C --> Parser
deactivate C
Parser --> Astra : AddGpaCommand
deactivate Parser

Astra -> C: execute(activities, UI, NB)
activate C

    create GpaEntry

    C -> GpaEntry: new GpaEntry(subject, grade, mc)
    activate GpaEntry
    C <-- GpaEntry
    deactivate GpaEntry

	C -> NB: getGpaList()
	activate NB
	C <-- NB
	deactivate NB

	C -> GL: add(entry)
	activate GL
	C <-- GL
	deactivate GL

	C -> NB: saveGpa()
	activate NB
    C <-- NB
    deactivate NB

C -> UI: showMessage("Added GPA entry: " + entry)
activate UI
C <-- UI
deactivate UI

C --> Astra: false
deactivate C
destroy C
Astra --> User

note left GpaEntry: GpaEntry is stored in GpaList\n hence not destroyed
@enduml