@startuml
' System-wide component/class overview
!include style.puml
hide member

package " " {
    class Astra
    class Command
    class Storage
    class Parser
    class Activity
    class Gpa
    class Ui
    class exception
}

Astra -right-> Parser

Parser ..> Command

Astra .down.> Command
Astra *-down- Command

Astra -left-> Storage
Astra *-left- Storage

Astra -up-> Activity
Astra *-up- Activity

Activity *- Gpa

Command -> Ui
Command .> exception

Astra -> Ui
Storage -> Ui


@enduml