@startuml
!include style.puml
actor User
participant Astra as ":Astra"
participant Parser as ":Parser"
participant C as ":ChangePriorityCommand"
participant AL as ":ActivityList"
participant UI as ":Ui"
participant NB as ":Notebook"

User -> Astra: "changepriority 3 /to 1"
activate Astra
Astra -> Parser: parse("changepriority 3 /to 1")
activate Parser
create C
Parser --> C: new ChangePriorityCommand(input)
activate C
return
return
Astra -> C: execute(AL, UI, NB)
activate C
C -> AL: getActivity(2)
activate AL
AL --> C: Task
C -> AL: reassign priorities (internal)
return
deactivate AL
C --> UI: showMessage("Priority updated: ...")
activate UI
return
C-->Astra : false
deactivate C
destroy C
Astra -> NB: writeToFile(activities)
activate NB
NB --> Astra
deactivate NB
Astra -> NB: saveToFile(activities)
activate NB
NB --> Astra
deactivate NB
Astra --> User
deactivate Astra

@enduml
