@startuml
!include style.puml
actor User
participant UI as "Ui"
participant Parser
participant C as "ChangeDeadlineCommand"
participant AL as "ActivityList"
participant T as "Task"
participant NB as "Notebook"

User -> UI: enter "changedeadline 3 /to 2025-10-31 18:00"
activate UI
UI -> Parser: parse(input)
activate Parser
create C
Parser -> C :new ChangeDeadlineCommand(input)
activate C
return
return ChangeDeadlineCommand
UI -> C: execute(activities, ui, notebook)
activate C
C -> AL: getActivity()
activate AL
return Task
C -> T: setDeadline(LocalDate, LocalTime)
C -> NB: saveToFile(activities)
return showMessage("Deadline updated for task: ...")
destroy C
@enduml
