@startuml
!include style.puml
actor User
participant Astra as ":Astra"

participant Parser as ":Parser"
participant C as ":ChangeDeadlineCommand"
participant AL as ":ActivityList"
participant T as ":Task"
participant UI as ":Ui"
participant NB as ":Notebook"

User -> Astra: "changedeadline 3 /to 2025-10-31 18:00"
activate Astra
Astra -> Parser: parse("changedeadline 3 /to 2025-10-31 18:00")
activate Parser
create C
Parser -> C :new ChangeDeadlineCommand(input)
activate C
return
return ChangeDeadlineCommand
 Astra -> C: execute(AL, UI, NB)
activate C
C -> AL: getActivity()
activate AL
return Task

C -> T: setDeadline(LocalDate, LocalTime)
activate T
T--> C
deactivate T
C -> UI : showMessage("Deadline updated for task: ...")
activate UI
return
deactivate UI
C -> NB: saveToFile(activities)
activate NB
return
C-->Astra : false
deactivate C
Astra-->User
destroy C
@enduml
