@startuml
hide footbox
Actor User
participant Astra
participant Parser
participant CheckCurrentCommand
participant ActivityList
participant "closestTasks: ArrayList<Task>" as tasks
participant Collections
participant Task
participant Ui

User -> Astra: input "checkCurrent 3"
activate Astra
Astra-> Parser : parse(input)
activate Parser
create CheckCurrentCommand
Parser -> CheckCurrentCommand: new CheckCurrentCommand(input)
activate CheckCurrentCommand
CheckCurrentCommand --> Parser
deactivate CheckCurrentCommand
Parser --> Astra
deactivate Parser

Astra -> CheckCurrentCommand: execute(AL,UL,NB)
activate CheckCurrentCommand
CheckCurrentCommand -> CheckCurrentCommand: getClosestTasks
activate CheckCurrentCommand
create tasks
CheckCurrentCommand -> tasks: new ArrayList<Task>
activate tasks
tasks --> CheckCurrentCommand:
deactivate tasks
loop For activity in ActivityList
    CheckCurrentCommand -> ActivityList: getActivity
    activate ActivityList
    ActivityList --> CheckCurrentCommand: activity
    deactivate ActivityList

    opt activity instanceof Task
        CheckCurrentCommand -> tasks : addActivity to ArrayList<Task>
        activate tasks
    end
end
tasks -> Collections: sort()
activate Collections
Collections --> tasks
deactivate Collections
Collections -[hidden]-> Collections
destroy Collections
tasks -->CheckCurrentCommand
deactivate tasks
CheckCurrentCommand --> CheckCurrentCommand
deactivate CheckCurrentCommand

CheckCurrentCommand -> Ui: show message
loop 3 or number > closestTasks.size()
    CheckCurrentCommand -> Task: toString
    activate Task
    Task --> CheckCurrentCommand: return String
    deactivate Task
    CheckCurrentCommand -> Ui: show message
end

CheckCurrentCommand --> Astra:false
deactivate CheckCurrentCommand
CheckCurrentCommand -[hidden]-> CheckCurrentCommand
destroy CheckCurrentCommand

Astra--> User

@enduml