@startuml
!include style.puml
Actor User
participant ":Astra" as Astra
participant ":Parser" as Parser
participant ":CheckCurrentCommand" as CheckCurrentCommand
participant "original_list: ActivityList" as original_list
participant "tasks: ArrayList<Task>" as tasks
participant ":Collections" as Collections
participant ":Task" as Task
participant ":Ui" as Ui
participant ":ActivityList" as ActivityList

User -> Astra : "checkcurrent"
activate Astra
Astra-> Parser: input "checkcurrent"
activate Parser
create CheckCurrentCommand
Parser -> CheckCurrentCommand: new CheckCurrentCommand(input)
activate CheckCurrentCommand
CheckCurrentCommand --> Parser
deactivate CheckCurrentCommand
Parser --> Astra
deactivate Parser

Astra -> CheckCurrentCommand: execute(AL, UI, NB)
activate CheckCurrentCommand
CheckCurrentCommand -> CheckCurrentCommand: getClosestTasks
activate CheckCurrentCommand
create tasks
CheckCurrentCommand -> tasks: new ArrayList<Task>
activate tasks
tasks --> CheckCurrentCommand: empty ArrayList<Task>
deactivate tasks
loop For activity in original ActivityList
    CheckCurrentCommand -> original_list: getActivity
    activate original_list
    original_list --> CheckCurrentCommand: activity
    deactivate original_list
    opt activity instanceof Task
        CheckCurrentCommand -> ActivityList: addActivity to ActivityList<Task>
        activate ActivityList
        return
        deactivate ActivityList
    end
end
CheckCurrentCommand -> Collections: sort the ActivityList<Task>
activate Collections
Collections --> CheckCurrentCommand
deactivate Collections
CheckCurrentCommand --> CheckCurrentCommand: ArrayList<Task> sublist
deactivate CheckCurrentCommand

CheckCurrentCommand -> Ui: showMessage()
activate Ui
return
deactivate Ui
loop For task in ActivityList
    CheckCurrentCommand -> Task: toString
    activate Task
    Task --> CheckCurrentCommand: return String
    deactivate Task
    CheckCurrentCommand -> Ui: showMessage()
    activate Ui
    return
    deactivate Ui
end
note left: do not exit the program
CheckCurrentCommand --> Astra: false
deactivate CheckCurrentCommand
Astra --> User
destroy CheckCurrentCommand
destroy tasks

@enduml