@startuml
!include style.puml
actor User
participant Astra as ":Astra"
participant Parser as ":Parser"
participant C as ":CheckPriorityCommand"
participant AL as ":ActivityList"
participant UI as ":Ui"

User -> Astra: "checkpriority"
activate Astra
Astra -> Parser: parse("checkpriority")
activate Parser
create C
Parser -->C : new CheckPriorityCommand()
activate C
return
return CheckPriorityCommand
Astra -> C: execute(AL, UI, NB)
activate C
C -> AL: getAllTasks()
activate AL
AL --> C: List<Task>
deactivate AL
C --> UI: showMessage(list ordered by priority)
activate UI
return
return false
return
destroy C
@enduml
