@startuml
!include style.puml
Actor User
participant Parser
participant CheckCurrentCommand
participant "original_list: ActivityList" as original_list
participant "tasks: ArrayList<Task>" as tasks
participant Collections
participant Task
participant Ui

User -> Parser: input "checkCurrent"
activate Parser
create CheckCurrentCommand
Parser -> CheckCurrentCommand: new CheckCurrentCommand(input)
activate CheckCurrentCommand
CheckCurrentCommand --> Parser
deactivate CheckCurrentCommand
Parser --> User
deactivate Parser

User -> CheckCurrentCommand: execute
activate CheckCurrentCommand
CheckCurrentCommand -> CheckCurrentCommand: getClosestTasks
activate CheckCurrentCommand
create tasks
CheckCurrentCommand -> tasks: new ArrayList<Task>
activate tasks
tasks --> CheckCurrentCommand: empty ArrayList<Task>
deactivate tasks
loop For activity in original ActivityList
    CheckCurrentCommand -> original_list: getActivity
    activate original_list
    original_list --> CheckCurrentCommand: activity
    deactivate original_list
    opt activity instanceof Task
        CheckCurrentCommand -> ActivityList: addActivity to ActivityList<Task>
    end
end
CheckCurrentCommand -> Collections: sort the ActivityList<Task>
activate Collections
Collections --> CheckCurrentCommand
deactivate Collections
CheckCurrentCommand --> CheckCurrentCommand: ArrayList<Task> sublist
deactivate CheckCurrentCommand

CheckCurrentCommand -> Ui: show message
loop For task in ActivityList
    CheckCurrentCommand -> Task: toString
    activate Task
    Task --> CheckCurrentCommand: return String
    deactivate Task
    CheckCurrentCommand -> Ui: show message
end

CheckCurrentCommand --> User: return false
note left: do not exit the program
deactivate CheckCurrentCommand

@enduml