@startuml
'https://plantuml.com/class-diagram
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor black
skinparam classBackgroundColor lightgrey
hide members

package Command as CommandPackage {
Class "<<interface>>\nCommand" as Command
Class "{abstract}\nXYZCommand" as XYZCommand
Class XYZCommands
Class QRSCommands
}

package Astra{}
package Activity{}
package Data{}
package Ui{}

Astra .right.> Command : <<create>>

XYZCommand .up.> Command



QRSCommands .down.> Command
QRSCommands -left-> Activity : modifies
QRSCommands -left--> Data : modifies
QRSCommands -left-> Ui


XYZCommands -left-|> XYZCommand
XYZCommands -up-> Activity : modifies
XYZCommands -left-> Data : modifies
XYZCommands -left-> Ui
note bottom of XYZCommands: XYZCommands = AddTaskCommand,\n CheckExamCommand, etc
note top of QRSCommands: QRSCommands = HelpCommand,\nListCommand, etc
note bottom of XYZCommand: XYZCommand = Abstract AddCommand,\nAbstract CheckCommand
@enduml