@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Command COMMAND_COLOR_T1
participant ":AddTaskCommand" as AddTaskCommand COMMAND_COLOR
end box

box DateTimeParser DATE_TIME_PARSER_COLOR_T1
participant ":DateTimeParser" as DateTimeParser DATE_TIME_PARSER_COLOR
end box

box ActivityList ACTIVITY_COLOR_T1
participant ":ActivityList" as ActivityList ACTIVITY_COLOR
end box

box Notebook DATA_COLOR_T1
participant ":Notebook" as Notebook DATA_COLOR
end box

[-> AddTaskCommand : execute(activites, ui notebook)
activate AddTaskCommand

AddTaskCommand -> DateTimeParser : parseDate(deadlineDateStr)
activate DateTimeParser

DateTimeParser --> AddTaskCommand : LocalDate
deactivate DateTimeParser

AddTaskCommand -> DateTimeParser : parseTime(deadlineDateTime)
activate DateTimeParser

DateTimeParser --> AddTaskCommand : LocalDate
deactivate DateTimeParser


@enduml
