@startuml
!include style.puml
actor User
participant Astra as ":Astra"
participant Parser as ":Parser"
participant C as ":ComputeGpaCommand"
participant NB as ":Notebook"
participant GL as ":GpaList"
participant UI as ":Ui"

User -> Astra: "gpa"
activate Astra
Astra -> Parser: parse("gpa")
activate Parser
create C
Parser -> C : new ComputeGpaCommand()
activate C
return
return ComputeGpaCommand
deactivate Parser
Astra -> C: execute(AL, UI, NB)
activate C
C -> NB: getGpaList()
activate NB
return
C -> GL: computeGpa()
activate GL
return
C -> UI: showMessage("Current GPA: %.2f")
activate UI
return
C --> Astra: false
deactivate C
Astra-->User
destroy C
@enduml