@startuml
'https://plantuml.com/sequence-diagram

hide footbox
actor User
participant ":Astra" as Astra
participant ":Parser" as Parser
participant ":DeleteCommand" as DeleteCommand
participant ":ActivityList" as ActivityList
participant ":Ui" as Ui
participant ":Notebook" as Notebook

User -> Astra : "delete 1"
activate Astra
Astra -> Parser : parse("delete 1")
activate Parser
create DeleteCommand
Parser -> DeleteCommand
activate DeleteCommand
return : DeleteCommand
return
deactivate Parser

Astra -> DeleteCommand : execute(AL, UI, NB)
activate DeleteCommand
DeleteCommand -> ActivityList : deleteActivity(1)
activate ActivityList
return
DeleteCommand -> Ui : ShowMessage()
activate Ui
return

return false
deactivate DeleteCommand
destroy DeleteCommand
Astra ->Notebook : saveToFile(activities)
activate Notebook
Notebook --> Astra
Astra -> Notebook : writeToFile(activities)
return
Astra --> User
deactivate Astra



@enduml