@startuml
'https://plantuml.com/sequence-diagram
hide footbox
actor User
participant Parser
participant UnmarkCommand
participant ActivityList
participant Task
participant Ui

User -> Parser : parse("unmark 3")
activate Parser
Parser -> UnmarkCommand : new UnmarkCommand(input)
activate UnmarkCommand
Parser <-- UnmarkCommand : return command
deactivate Parser

User -> UnmarkCommand : execute(activities, ui, notebook)
activate UnmarkCommand
UnmarkCommand -> ActivityList : getActivity(index - 1)
activate ActivityList
ActivityList --> UnmarkCommand : Activity
deactivate ActivityList
UnmarkCommand -> Task : clearIsComplete()
activate Task
deactivate Task
UnmarkCommand -> Ui : showMessage("Unmarked: #3 ...")
activate Ui
deactivate Ui
deactivate UnmarkCommand
@enduml